Allow ChaincodeEvents to resume after a specific transaction ID
hyperledger/fabric-protos pull request #77
Opened 2022-03-13 13:10 UTC by bestbeforetoday

Add a `previous_transaction_id` field to the ChaincodeEventsRequest message so the client can specify a transaction ID, up to which chaincode events should be ignored and not returned to the client.

2022-03-15 11:34 UTC, andrew-coleman requested changes

2022-03-15 11:34 UTC, andrew-coleman commented on gateway/gateway.proto
> +    // Only returns events after this ransaction ID. Transactions up to and including this one should be ignored. This
ransactioID -> transactionID

2022-03-15 11:35 UTC, andrew-coleman approved these changes

2022-03-15 11:35 UTC, bestbeforetoday commented on gateway/gateway.proto
> +    // Only returns events after this ransaction ID. Transactions up to and including this one should be ignored. This
👍

2022-03-15 11:36 UTC, merged

2022-10-05 18:50 UTC, denyeart commented
@Mergifyio backport release-2.4